services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - frontend
    networks:
      - appnet
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
