name: Backend Tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test-backend:
    name: Run backend lint, unit and e2e tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nesttracker_test
          POSTGRES_USER: nestuser
          POSTGRES_PASSWORD: nestpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U nestuser -d nesttracker_test" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 10

    env:
      NODE_ENV: test
      DATABASE_URL_TEST: postgresql://nestuser:nestpassword@localhost:5432/nesttracker_test
      # Secrets needed by the app during tests; override in repo/org secrets if desired
      JWT_SECRET: ${{ secrets.CI_JWT_SECRET || 'ci-jwt-secret-at-least-32-characters-long-123456' }}
      TWOFA_ENCRYPT_KEY: ${{ secrets.CI_TWOFA_ENCRYPT_KEY || 'ci-twofa-encryption-key-at-least-32-chars-1234' }}
      TWOFA_ENCRYPT_SALT: ${{ secrets.CI_TWOFA_ENCRYPT_SALT || 'ci-twofa-salt-at-least-16' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install dependencies (backend)
        working-directory: backend
        run: npm ci

      - name: Lint (backend)
        working-directory: backend
        run: npm run lint

      - name: Run unit tests (backend)
        working-directory: backend
        run: npm test -- --runInBand

      - name: Run e2e tests (backend)
        working-directory: backend
        run: npm run test:e2e -- --runInBand
